# Generated by Django 4.2 on 2023-04-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_profile_bio'),
        ('app_blog', '0002_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='app_auth.profile', verbose_name='profile'),
        ),
    ]
